
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 01 11:27:48 CST 2019
//----------------------------------------------------

package servidor.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tElseif = 2;
  public static final int tWrite = 21;
  public static final int tIgual = 61;
  public static final int tDpar = 63;
  public static final int tWhile = 42;
  public static final int tRecord = 23;
  public static final int tMenorigual = 80;
  public static final int tThen = 41;
  public static final int tDivision = 75;
  public static final int tTo = 18;
  public static final int tBoolean = 6;
  public static final int tMenor = 82;
  public static final int tMultiplicacion = 74;
  public static final int tTrunk = 54;
  public static final int tBreak = 56;
  public static final int tModulo = 77;
  public static final int tDosp = 67;
  public static final int nEntero = 84;
  public static final int tIpar = 62;
  public static final int tDcor = 65;
  public static final int tPotencia = 76;
  public static final int tComa = 68;
  public static final int tPunto = 69;
  public static final int tFor = 17;
  public static final int tTrue = 28;
  public static final int tAsignacion = 60;
  public static final int tChar = 5;
  public static final int tDefault = 38;
  public static final int tDownto = 35;
  public static final int tDistinto = 78;
  public static final int tIcor = 64;
  public static final int tReplace = 49;
  public static final int tResta = 73;
  public static final int nDecimal = 83;
  public static final int tElse = 39;
  public static final int tTouppercase = 52;
  public static final int tWriteln = 22;
  public static final int nIdentificador = 85;
  public static final int tMayorigual = 79;
  public static final int tTolowercase = 51;
  public static final int tRepeat = 33;
  public static final int tSuma = 72;
  public static final int tBegin = 15;
  public static final int tLength = 48;
  public static final int tFree = 27;
  public static final int tEnd = 16;
  public static final int tRound = 55;
  public static final int tDospuntos = 71;
  public static final int tExit = 58;
  public static final int tProgram = 20;
  public static final int tProcedure = 40;
  public static final int tAnd = 30;
  public static final int nCadena = 87;
  public static final int tString = 8;
  public static final int EOF = 0;
  public static final int tCase = 37;
  public static final int tConst = 12;
  public static final int tUntil = 34;
  public static final int tEquals = 53;
  public static final int tMayor = 81;
  public static final int tTochararray = 50;
  public static final int tDo = 19;
  public static final int tWith = 24;
  public static final int tFunction = 36;
  public static final int tUses = 44;
  public static final int error = 1;
  public static final int tNand = 45;
  public static final int tReal = 4;
  public static final int tCharat = 47;
  public static final int tType = 10;
  public static final int tTresp = 66;
  public static final int tRead = 59;
  public static final int tPuntocoma = 70;
  public static final int tToken = 86;
  public static final int tContinue = 57;
  public static final int tInteger = 3;
  public static final int tFalse = 29;
  public static final int tArray = 13;
  public static final int tMalloc = 25;
  public static final int tSizeof = 26;
  public static final int tWord = 7;
  public static final int tOr = 32;
  public static final int nCaracter = 88;
  public static final int tNot = 31;
  public static final int tIf = 43;
  public static final int tNor = 46;
  public static final int tNil = 9;
  public static final int tVar = 11;
  public static final int tOf = 14;
}

